// VIDEO
export const ALL_VIDEOS_LOADED = 'ALL_VIDEOS_LOADED';
export const VIDEO_LOADED = 'VIDEO_LOADED';
export const ALL_RELATED_VIDEOS_LOADED = 'ALL_RELATED_VIDEOS_LOADED';
export const VIDEO_ERROR = 'VIDEO_ERROR';

// WEATHER
export const WEATHER_DATA_LOADED = 'WEATHER_DATA_LOADED';
export const WEATHER_ERROR = 'WEATHER_ERROR';
