// VIDEO
export const ALL_VIDEOS_LOADED = 'ALL_VIDEOS_LOADED';
export const VIDEO_LOADED = 'VIDEO_LOADED';
export const ALL_RELATED_VIDEOS_LOADED = 'ALL_RELATED_VIDEOS_LOADED';
export const VIDEO_ERROR = 'VIDEO_ERROR';
